### ISSUE TITLE
'listener_certificate_name' is undefined

### ISSUE THREAD

**Issue by dan-h** [eumel8/otc_elb#1]
In lookup.yml, 

```
- name: Set fact listener_certificate_id for elb if listener_certificate_name is defined
  set_fact:
    listener_certificate_id: "{{ (listener_certificate_result.content|from_json)|json_query(\"certificates[?name=='\" + listener_certificate_name + \"'].id|[0]\") }}"
  when:
    - listener_name is defined
```

**listener_name** should be replaced with **listener_certificate_name**.

```
- name: Set fact listener_certificate_id for elb if listener_certificate_name is defined
  set_fact:
    listener_certificate_id: "{{ (listener_certificate_result.content|from_json)|json_query(\"certificates[?name=='\" + listener_certificate_name + \"'].id|[0]\") }}"
  when:
    - listener_certificate_name is defined
```
